### ISSUE TITLE
Add a PriorityRoundRobin

### ISSUE THREAD

**Issue by eyas-ranjous** [eyas-ranjous/round-robin-js#7]
- item selection based on priority
- use PriorityQueue

**Comment by martinAlt335** [comment]
Hey eyas-ranjous, thanks for the awesome package. I just wanted to ask about this feature. Would've loved the ability to set weights for each item in the round robin set. The package is nicely written and I've integrated with it but yeah would've been complete if we could 'prioritise' certain items.

**Comment by eyas-ranjous** [comment]
Hi Martin. Yes I was going to do this one alone but thought it won't be used, re-opening it

**Comment by martinAlt335** [comment]
Would just like to leave a comment. For my current use-case I've managed to shift to no longer needing a weighted robin queue, although in future use cases if it may come up for whatever reason, having this feature at ones disposal is great. Cheers.

**Comment by eyas-ranjous** [comment]
ok thanks for the update, I'm just finishing releasing a new version of the priority queue, and will move to this feature right after.

**Comment by eyas-ranjous** [comment]
v3 released https://github.com/eyas-ranjous/round-robin-js#round-robin-js
