### ISSUE TITLE
Feature Request: Add method to delete an item based on the value (not key)

### ISSUE THREAD

**Issue by andrei93r** [eyas-ranjous/round-robin-js#8]
As context, I want to use this library to request information from multiple providers based which have different quota's to respect.

**Comment by eyas-ranjous** [comment]
@andrei93r I have opened a draft PR for your request, and will be finalizing it soon, mainly you will be able after releasing this to `deleteByKey` that deletes a single item from the table & `deleteByValue(value)` that deletes all items that has a value that match the one to be deleted. Let me know there is something else missing, also it'd be helpful for me if you can provide me with a code snippet that shows your use case, to make sure I'm building it for easy use.

**Comment by eyas-ranjous** [comment]
v2 is released with deleteByValue https://github.com/eyas-ranjous/round-robin-js#deletebyvaluecb
